//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InkPlatform {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("InkPlatform.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already Connected.
        /// </summary>
        internal static string ALREADY_CONNECTED {
            get {
                return ResourceManager.GetString("ALREADY_CONNECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string CANCEL_TEXT {
            get {
                return ResourceManager.GetString("CANCEL_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot Connect.
        /// </summary>
        internal static string CANNOT_CONNECT {
            get {
                return ResourceManager.GetString("CANNOT_CONNECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string CLEAR_TEXT {
            get {
                return ResourceManager.GetString("CLEAR_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CRC.
        /// </summary>
        internal static string CRC {
            get {
                return ResourceManager.GetString("CRC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Busy.
        /// </summary>
        internal static string DEVICE_BUSY {
            get {
                return ResourceManager.GetString("DEVICE_BUSY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Fail.
        /// </summary>
        internal static string DISPLAY_FAIL {
            get {
                return ResourceManager.GetString("DISPLAY_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File not found.
        /// </summary>
        internal static string FILE_NOT_FOUND {
            get {
                return ResourceManager.GetString("FILE_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to getSerialPorts.exe not found.
        /// </summary>
        internal static string GetSerialPortsNotFound {
            get {
                return ResourceManager.GetString("GetSerialPortsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graphics Image Too Long.
        /// </summary>
        internal static string GRAPHICS_IMAGE_TOO_LONG {
            get {
                return ResourceManager.GetString("GRAPHICS_IMAGE_TOO_LONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graphics Wrong Encoding Type.
        /// </summary>
        internal static string GRAPHICS_WRONG_ENCODING_TYPE {
            get {
                return ResourceManager.GetString("GRAPHICS_WRONG_ENCODING_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graphics Wrong Parameters.
        /// </summary>
        internal static string GRAPHICS_WRONG_PARAMETERS {
            get {
                return ResourceManager.GetString("GRAPHICS_WRONG_PARAMETERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graphics Zlib Error.
        /// </summary>
        internal static string GRAPHICS_ZLIB_ERROR {
            get {
                return ResourceManager.GetString("GRAPHICS_ZLIB_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initialization Failed.
        /// </summary>
        internal static string INIT_FAIL {
            get {
                return ResourceManager.GetString("INIT_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read Layout File Failed.
        /// </summary>
        internal static string LAYOUT_FAIL {
            get {
                return ResourceManager.GetString("LAYOUT_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layout not found.
        /// </summary>
        internal static string LAYOUT_NOT_FOUND {
            get {
                return ResourceManager.GetString("LAYOUT_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Connected.
        /// </summary>
        internal static string NOT_CONNECTED {
            get {
                return ResourceManager.GetString("NOT_CONNECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Supported.
        /// </summary>
        internal static string NOT_SUPPORTED {
            get {
                return ResourceManager.GetString("NOT_SUPPORTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing Parameter.
        /// </summary>
        internal static string NULL_PARAM {
            get {
                return ResourceManager.GetString("NULL_PARAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OK_TEXT {
            get {
                return ResourceManager.GetString("OK_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string SUCCESS {
            get {
                return ResourceManager.GetString("SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USB.
        /// </summary>
        internal static string USB {
            get {
                return ResourceManager.GetString("USB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Cancelled.
        /// </summary>
        internal static string USER_CANCELLED {
            get {
                return ResourceManager.GetString("USER_CANCELLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wacom.
        /// </summary>
        internal static string WACOM {
            get {
                return ResourceManager.GetString("WACOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wintab Device.
        /// </summary>
        internal static string WINTAB_DEVICE {
            get {
                return ResourceManager.GetString("WINTAB_DEVICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong Report ID.
        /// </summary>
        internal static string WRONG_REPORT_ID {
            get {
                return ResourceManager.GetString("WRONG_REPORT_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong State.
        /// </summary>
        internal static string WRONG_STATE {
            get {
                return ResourceManager.GetString("WRONG_STATE", resourceCulture);
            }
        }
    }
}
